dont_save: false
exp:
  d1_name: sample
  d1_split: split1
  d2_name: sample
  d2_split: split2
  max_generate: 256
  name: sample_experiment
model:
  name: meta-llama/Llama-3.2-1B-Instruct
  type: hf
  use_flash_attn: true
name: sample_run
name_id: sample_run_fad916870a1b42638cd1105507d83237
run_id: fad916870a1b42638cd1105507d83237
save_context: false
save_dir: runs/
save_path: runs/sample_run_fad916870a1b42638cd1105507d83237
