dont_save: null
exp:
  max_generate: 256
  name: sample_experiment
model:
  name: meta-llama/Llama-3.2-1B-Instruct
  type: hf
  use_flash_attn: true
name: default
name_id: null
run_id: null
save_context: false
save_dir: runs/
save_path: null
