exp:
  name: explicit_questions_experiment
  prompt_name: neutral_with_gpt_best_practices_better_word_for_attitude.txt
  num_in_context_samples: 4
  max_num_generated_responses: 10
  max_generate: 1024
model:
  use_flash_attn: false
name: explicit_experimental_sample_test
save_context: false
save_dir: runs/explicit/experimental