exp:
  num_in_context_samples: 2
  name: implicit_questions_experiment
  prompt_name: april_9_prompt0.txt
  max_generate: 1000000
  max_num_generated_responses: 5
  d1_name: reddit
  d1_split: funny
  d2_name: reddit
  d2_split: showerthoughts

model:
  use_flash_attn: false
name: subreddit_run
save_context: false
save_dir: runs/implicit/experimental