
exp:
  name: reddit_self_scoring_experiment
  num_outputs_per_prompt: 1
  max_generate: 2000
  prompt_name: april_30_prompt_self_scoring_continuation_from_prev_output.txt
model:
  gen:
    do_sample: true
    max_new_tokens: 2000
    temperature: 0.6
    top_p: 0.9
  name: meta-llama/Llama-3.2-3B-Instruct
  quantize: false
  type: hf
  use_flash_attn: false
name: reddit_self_scoring
name_id: null
run_id: null
save_context: true
save_dir: runs/reddit/implicit
save_path: null
short_circuit: false
verbose: True
